# Generated by Django 5.1.6 on 2025-03-01 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_author_alter_post_content_alter_post_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='caption',
            new_name='tag',
        ),
    ]
